[package]
name = "srcerr"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"
description = "User friendly errors from source data."
repository = "https://github.com/azriel91/srcerr"
documentation = "https://docs.rs/srcerr/"
readme = "README.md"
keywords = ["error", "format"]
license = "MIT OR Apache-2.0"

[dependencies]
ansi_term = { version = "0.12.1", optional = true }

[features]
default = ["ansi_color"]
ansi_color = ["ansi_term"]
